#Webui can be found at <your-ip>:32400/web

version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:1.32.7
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=FI
      - VERSION=docker
      - PLEX_CLAIM= #optional
    ports:
      - 32400:32400/tcp
    volumes:
      - /mnt/sda1/PLEXCONFIG:/config
      - /mnt/sda1/SERIES:/tv
      - /mnt/sda1/MOVIES:/movies
    restart: unless-stopped